module.exports = {
  apps: [
    {
      name: "tqd-api",
      cwd: "/opt/timquanhday/apps/api",
      script: "src/index.js",
      interpreter: "node",
      env: {
        PORT: "3001",
        DB_HOST: "127.0.0.1",
        DB_PORT: "3306",
        DB_USER: "coffee",
        DB_PASSWORD: "coffee_mvp_2026",
        DB_NAME: "timquanhday",
        JWT_SECRET: "tqd-jwt-secret-2026",
        JWT_REFRESH_SECRET: "tqd-refresh-secret-2026",
        CORS_ORIGIN: "https://timquanhday.de,https://staging.timquanhday.de",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/opt/timquanhday/logs/api-error.log",
      out_file: "/opt/timquanhday/logs/api-out.log",
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: "tqd-staging",
      cwd: "/opt/timquanhday/staging/apps/api",
      script: "src/index.js",
      interpreter: "node",
      env: {
        PORT: "3002",
        DB_HOST: "127.0.0.1",
        DB_PORT: "3306",
        DB_USER: "coffee",
        DB_PASSWORD: "coffee_mvp_2026",
        DB_NAME: "timquanhday",
        JWT_SECRET: "tqd-jwt-secret-staging",
        JWT_REFRESH_SECRET: "tqd-refresh-secret-staging",
        CORS_ORIGIN: "https://staging.timquanhday.de",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/opt/timquanhday/logs/staging-error.log",
      out_file: "/opt/timquanhday/logs/staging-out.log",
      max_restarts: 10,
      restart_delay: 3000,
    },
  ],
};